import os

"""
定义恶意路径 信心指数默认为1， 范围1-100，1 信心度最高
"""
PATH_PATTERNS = {
    "getkey?aaa=1&e=3":2,
    "inputParam?param=":3,
    "set.php?ciyu":1,
    "keywords='+this.state.mnemonicWord+'":1,
    "mnemonic+'&code=10000&source":2,
    "toString()+'&code=10000&source=android":2,
    "keywords='+t.mnemonic+'&code=10000":1,
    "aid=10&wt=1&os=1&key=": 1,
    "ciyu.php?ciyu=": 1,
    "getkey?e=": 1,
    "getmnemonic?type=": 1,
    "c=9&app=1&client=2&o=": 1,
    "ciyu=": 1,
    "ciyu.php": 1,
    "from=c&k=": 1,
    "getKey=true&pri=": 1,
    "SecureIF?VerToken=": 1,
    "qudaobao=android&mnemonic=": 1,
    "getmnemonic": 1,
    "&code=drseo828": 1,
    "'+ciyu+'&code=348608'":1
}

"""
定义恶意域名 信心指数默认为1
"""
DOMAIN_PATTERNS = {
    "intoken.tw":1,
    "imtoke.net":1,
    "geqianff386.xyz":1,
    "qianff364.xyz":1,
    "geqianxz383.xyz":1,
    "qianxz364.xyz":1,
    "geqianxz385.xyz":1,
    "qianxz361.xyz":1,
    "qianff358.xyz":1,
    "geqianff381.xyz":1,
    "geqianxz378.xyz":1,
    "qianxz357.xyz":1,
    "qianff354.xyz":1,
    "geqianff358.xyz":1,
    "geqianff382.xyz":1,
    "wzsyydz.com":1,
    "jljc888.co":1,
    "hotea.lol":1,
    "tokenlinktpc.xyz":1,
    "cloudshop1.net":1,
    "usdtru.com":1,
    "imtokencn.xyz":1,
    "wxyij.xyz":1,
    "bindoke.icu":1,
    "bindoke.click":1,
    "lmtoken.sbs":1,
    "lmtoken.click":1,
    "hhttirr.com":1,
    "ktsr.cc":1,
    "tronusdt.co":1,
    "usdtstudio.cc":1,
    "ch56789.com":1,
    "skyyun.org":1,
    "qdyum.com":1,
    "cpufo.com":1,
    "im-token.skin":1,
    "tokennim.cn":1,
    "reuvip.com":1,
    "kk9.ink":1,
    "msms.life":1,
    "bindtoken.click":1,
    "dtfacai.com":1,
    "usdtcheckbot.top":1,
    "8029.com.cn":1,
    "xazydz.com":1,
    "tronous.com":1,
    "fgffgg.icu":1,
    "fliok.top":1,
    "telegact-admioo.top":1,
    "tokenpoccket.shop":1,
    "dthbkefu.vip":1,
    "n5a.net":1,
    "telegaem-gif.top":1,
    "telegaem-ych.top":1,
    "9725999.mom":1,
    "telegaem-admihj2.top":1,
    "telegaem-admihj.top":1,
    "newdatapro.com":1,
    "ellgip.cn":1,
    "amm-bot.top":1,
    "imtokencc.icu":1,
    "uufafa.com":1,
    "metamesks.io":1,
    "tokenpocketn.co":1,
    "timis.pro":1,
    "okxusd.cn":1,
    "okxtd.cn":1,
    "okxpayl.cn":1,
    "imtokenn.xyz":1,
    "manageweb.xyz":1,
    "imtokeu.net":1,
    "timiswork.top":1,
    "xxsgzs.cn":1,
    "fun-defi.xyz":1,
    "fakkmm.com":1,
    "usdteth.com":1,
    "dd1145.com":1,
    "tel-eth.com":1,
    "eth-cvc89.com":1,
    "uforce.shop":1,
    "rep-eth.com":1,
    "starwolf.cn":1,
    "ioos.top":1,
    "tonkencn.cn":1,
    "dy6188.ink":1,
    "9264lll.com":1,
    "wallethome.org":1,
    "mywode.org":1,
    "ctiaodnveif3.com":1,
    "btiaodicnsne2.com":1,
    "kkkj.me":1,
    "maskdefi.xyz":1,
    "tronscan.red":1,
    "8hg70.com":1,
    "5488a.com":1,
    "jjhgmq.com":1,
    "uforce.fun":1,
    "wiinsoft.net":1,
    "easdown.net":1,
    "appdown876.net":1,
    "appdown558.net":1,
    "rep-eth.net":1,
    "cecdd.com":1,
    "wonder123.shop":1,
    "imtoken-hk.icu":1,
    "69258.net":1,
    "cc93777.com":1,
    "tokenviewss.com":1,
    "9ovs.com":1,
    "walletyy.org":1,
    "1mwap.com":1,
    "ceshi.in":1,
    "cpapisa.top":1,
    "tron-traceon.com":1,
    "payple772.life":1,
    "webdao.vip":1,
    "payple633.info":1,
    "suiswap.me":1,
    "imtokem.bond":1,
    "accreditation.top":1,
    "thistlesisters.com":1,
    "uuuusdtt.asia":1,
    "12377.top":1,
    "payple527.info":1,
    "6kff.cn":1,
    "hgfacai.com":1,
    "223273.pw":1,
    "moviesbill.com":1,
    "123solute.xyz":1,
    "metamasks.cyou":1,
    "metamk.icu":1,
    "usdtch.com":1,
    "mathwallets.life":1,
    "westore.top":1,
    "onis9.com":1,
    "metamesk.tv":1,
    "tokenvieu.com":1,
    "maitui.top":1,
    "okt-okxpay.top":1,
    "tokeopocket.site":1,
    "ecoecokeep.com":1,
    "kinlin.im":1,
    "sssuu.com":1,
    "toiken.cc":1,
    "imtoken-token-im.com":1,
    "aligpt.buzz":1,
    "satsun.cn":1,
    "ddg.buzz":1,
    "trc1oym.com":1,
    "sbsbs.sbs":1,
    "amttc522.com":1,
    "resource-av.com":1,
    "bitproso.top":1,
    "boxin-app.com":1,
    "tnblyxggphipml8bsq2tgf3e96nkkubhhs.icu":1,
    "imtoken11.com":1,
    "shangpinshidai.com":1,
    "dy168888.vip":1,
    "123sheet.life":1,
    "cnimtoken.cyou":1,
    "od-shop.com":1,
    "jxlbusd.com":1,
    "imtokencn.club":1,
    "okx-miner.bio":1,
    "matemask.tv":1,
    "mites-app.com":1,
    "nez9002.com":1,
    "dcoinmining.com":1,
    "imqianbai.vip":1,
    "nhdaohang.xyz":1,
    "mining-leaders.pro":1,
    "gxfcgxfc.xyz":1,
    "ybihoc.cn":1,
    "lifeform.ac":1,
    "im-token.town":1,
    "metamask6.com":1,
    "etherapp.cc":1,
    "zgank.com":1,
    "trustwallet-eth.pro":1,
    "liu66.club":1,
    "imitoken.icu":1,
    "lvapp.cc":1,
    "telegramage.ltd":1,
    "imtoken.ceo":1,
    "iazada.space":1,
    "bnbm.site":1,
    "usdttrx1.com":1,
    "yuedua.cyou":1,
    "69kkh.cc":1,
    "kapmc.xyz":1,
    "juexiuluo.pro":1,
    "vipimtoken.cn":1,
    "tg-php888888.xyz":1,
    "nwdyaz2o.club":1,
    "5yiwo05x.club":1,
    "fingeryu.com":1,
    "poolxw.com":1,
    "eth-cvc79.com":1,
    "eth-cvc.com":1,
    "eth-cvc78.com":1,
    "eth-cvc68.com":1,
    "eth-cvc668.com":1,
    "cylhy.com":1,
    "otcusdt.top":1,
    "shuanglong.cc":1,
    "xms83.com":1,
    "imtoken.pt":1,
    "123loft.top":1,
    "qq1233.com":1,
    "shopifyli.com":1,
    "usdtskyou.top":1,
    "tokenvim.com":1,
    "xinbi.lol":1,
    "tokenipocket.vip":1,
    "ahegai837162.win":1,
    "9cur8sjg.club":1,
    "9jrcyb4a.club":1,
    "rt98zcaf.club":1,
    "h005j5ab.club":1,
    "defitrust.top":1,
    "tokcnpocket.pro":1,
    "facaiqwertyuiopzxc.com":1,
    "im-tokeno.com":1,
    "zhengrongshanghui.com":1,
    "veg.gold":1,
    "otcusdt.shop":1,
    "token-imm.com":1,
    "777gg.com":1,
    "hshoutai.com":1,
    "tronusdt1.com":1,
    "tronusdt8.com":1,
    "kt357.com":1,
    "wgeonline.com":1,
    "fun-defi.com":1,
    "ly88bet.com":1,
    "ll2022.com":1,
    "lm-token.online":1,
    "dingdangim.net":1,
    "doudouyi.top":1,
    "demo-rui.top":1,
    "smlab.club":1,
    "cai5888.club":1,
    "cai6888.xyz":1,
    "tronscan.tech":1,
    "bittkeep.com":1,
    "lhkj777.fun":1,
    "lhkj777.tech":1,
    "wwoyfg7e.xyz":1,
    "onis.pro":1,
    "wkudim.com":1,
    "932811.com":1,
    "931698.com":1,
    "imtokenm.pro":1,
    "tokenvims.com":1,
    "eth-cvc69.com":1,
    "lzawallet888.com":1,
    "app8.fun":1,
    "exmbztrbecls.com":1,
    "geqianxz382.xyz":1,
    "bvip.dev":1,
    "ceshi-imtoken.cn":1,
    "tpimpay.app":1,
    "a171im.com":1,
    "tokeww.com":1,
    "big76.com":1,
    "big77.com":1,
    "htim888.com":1,
    "tsw7t.com":1,
    "a191imim.com":1,
    "imtokeninc.cn":1,
    "xdhbj.com":1,
    "iimtoken.app":1,
    "shakna118.com": 1,
    "866886.icu": 1,
    "imtokenwat.com": 1,
    "a888newapi.xyz": 1,
    "foxabc.cc": 1,
    "funnel.rocks": 1,
    "upimtoken.com": 1,
    "eiwat.cn": 1,
    "bitkeeperwallet.com": 1,
    "a168im.com": 1,
    "hhbbc.org.cn": 1,
    "a112imim.com": 1,
    "newokpo.com": 1,
    "xbtcx5.com": 1,
    "a158im.xyz": 1,
    "tokenlonapis.com": 1,
    "im168168.com": 1,
    "dowm9.com": 1,
    "a182im.com": 1,
    "imdolsoel.com": 1,
    "imtoen.app": 1,
    "uniswaper.me": 1,
    "a135imiss2.com": 1,
    "setimtoken.com": 1,
    "tokenio.fun": 1,
    "hhbbk.org.cn": 1,
    "35win.cc": 1,
    "topyni.com": 1,
    "kkkkw.org.cn": 1,
    "intokenmn.com": 1,
    "im6.app": 1,
    "baby788.com": 1,
    "a181imiimm.com": 1,
    "lmtoken.cc": 1,
    "imqb2023.app": 1,
    "tokenexpert.net": 1,
    "sxsfcc.com": 1
}

HASH_PATTERNS = {
    "fdfa25b954480a44d2632b0aa2fd2a2f":"tokenio.fun",
    "8722294c127d7da9ac230e5ded2910a7":"tokenio.fun"
}

"""
日志输出等级
"""
LOG_LEVEL = "ERROR"

"""
目录设置
"""
# 项目脚本的目录
PROJECT_DIR = os.path.dirname(__file__)
# 报告存放目录
REPORT_DIR = os.path.join(PROJECT_DIR, "report")
# 临时数据存放目录
TEMP_DIRECTORY = os.path.join(PROJECT_DIR, "temp_extracted")
# 恶意 APK 存放目录
APK_DIRECTORY = os.path.join(PROJECT_DIR, "apkStore")

"""
分析上下文范围设置
"""
CONTEXT_LENGTH = 200 # 总长度200
CONTEXT_RANGE = 100

"""
使用ANSI转义序列来定义颜色
主要用于在终端或命令行界面中增加文本的可读性和美观
W (White): \033[0m - 默认的文字颜色。
G (Green): \033[1;32m - 亮绿色。0 为普通绿色
R (Red): \033[1;31m - 亮红色。
O (Orange): \033[1;33m - 亮黄色，通常被解释为橙色。
B (Blue): \033[1;34m - 亮蓝色。

example:
R 使 "xxoo**--==:" 这部分文本显示为亮红色。
W 重置颜色，使之后的文本恢复默认颜色。
G 使 "Hello world" 这部分文本显示为亮绿色。
最后的 W 再次重置颜色，以确保之后的文本不受影响。

print(R,"xxoo**--==:",W,G,"Hello world",W)
print(O,"xxoo**--==:",W,B,"Hello world",W)
"""
W = '\033[0m'
G = '\033[0;32m'
G1 = '\033[1;32m'
R = '\033[0;31m'
O = '\033[0;33m'
B = '\033[1;34m'

"""
APK 壳检测
"""
SHELLFEATURE = {
    "libchaosvmp.so": "娜迦",
    "libddog.so": "娜迦",
    "libfdog.so": "娜迦",
    "libedog.so": "娜迦企业版",
    "libexec.so": "爱加密",
    "libexecmain.so": "爱加密",
    "ijiami.dat": "爱加密",
    "ijiami.ajm": "爱加密企业版",
    "libsecexe.so": "梆梆免费版",
    "libsecmain.so": "梆梆免费版",
    "libSecShell.so": "梆梆免费版",
    "libDexHelper.so": "梆梆企业版",
    "libDexHelper-x86.so": "梆梆企业版",
    "libprotectClass.so": "360 加固",
    "libjiagu.so": "360 加固",
    "libjiagu_art.so": "360 加固",
    "libjiagu_x86.so": "360 加固",
    "libegis.so": "通付盾",
    "libNSaferOnly.so": "通付盾",
    "libnqshield.so": "网秦",
    "libbaiduprotect.so": "百度",
    "aliprotect.dat": "阿里聚安全",
    "libsgmain.so": "阿里聚安全",
    "libsgsecuritybody.so": "阿里聚安全",
    "libmobisec.so": "阿里聚安全",
    "libtup.so": "腾讯",
    "libexec.so": "腾讯",
    "libshell.so": "腾讯",
    "mix.dex": "腾讯",
    "lib/armeabi/mix.dex": "腾讯",
    "lib/armeabi/mixz.dex": "腾讯",
    "libtosprotection.armeabi.so": "腾讯御安全",
    "libtosprotection.armeabi-v7a.so": "腾讯御安全",
    "libtosprotection.x86.so": "腾讯御安全",
    "libnesec.so": "网易易盾",
    "libAPKProtect.so": "APKProtect",
    "libkwscmm.so": "几维安全",
    "libkwscr.so": "几维安全",
    "libkwslinker.so": "几维安全",
    "libx3g.so": "顶像科技",
    "libapssec.so": "盛大",
    "librsprotect.so": "瑞星"
}